--- #YAML:1.0
name:                Squatting
version:             0.20
abstract:            a Camping-inspired Web Microframework for Perl
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Continuity:                    0.991
    Data::Dump:                    0
    HTTP::Daemon:                  0
    JSON::XS:                      0
    Shell::Perl:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - John Beppu <beppu@cpan.org>
