--- #YAML:1.0
name:               Squatting
version:            0.60
abstract:           A Camping-inspired Web Microframework for Perl
author:
    - John BEPPU <beppu@cpan.org>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::C3::Componentised:  0
    Clone:                0
    Continuity:           0.991
    Data::Dump:           0
    HTTP::Daemon:         0
    HTTP::Response:       0
    IO::All:              0
    JSON::XS:             0
    Shell::Perl:          0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
no_index:
    directory:
        - eg
        - t
