---
abstract: 'A Camping-inspired Web Microframework for Perl'
author:
  - 'John BEPPU <beppu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.130870'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Squatting
no_index:
  directory:
    - t
    - inc
requires:
  Class::C3::Componentised: 0
  Clone: 0
  Continuity: 0.991
  Data::Dump: 0
  HTTP::Daemon: 0
  HTTP::Response: 0
  IO::All: 0
  JSON::XS: 0
  Shell::Perl: 0
  Test::More: 0
resources:
  repository: http://github.com/beppu/squatting
version: 0.82
no_index:
    directory:
        - eg
        - t
